import 'package:myputt/models/data/chart/chart_point.dart';

final List<ChartPoint> emptyStateChartPoints = [
  ChartPoint(decimal: 5, timeStamp: 0, distance: 0, index: 1),
  ChartPoint(decimal: 6, timeStamp: 0, distance: 0, index: 2),
  ChartPoint(decimal: 8, timeStamp: 0, distance: 0, index: 3),
  ChartPoint(decimal: 7.5, timeStamp: 0, distance: 0, index: 4),
  ChartPoint(decimal: 9, timeStamp: 0, distance: 0, index: 5),
  ChartPoint(decimal: 5, timeStamp: 0, distance: 0, index: 6),
  ChartPoint(decimal: 10, timeStamp: 0, distance: 0, index: 7),
  ChartPoint(decimal: 11, timeStamp: 0, distance: 0, index: 8),
  ChartPoint(decimal: 12, timeStamp: 0, distance: 0, index: 9),
  ChartPoint(decimal: 11, timeStamp: 0, distance: 0, index: 10),
  ChartPoint(decimal: 13, timeStamp: 0, distance: 0, index: 11),
  ChartPoint(decimal: 12, timeStamp: 0, distance: 0, index: 12),
  ChartPoint(decimal: 13, timeStamp: 0, distance: 0, index: 13),
  ChartPoint(decimal: 11, timeStamp: 0, distance: 0, index: 14),
  ChartPoint(decimal: 11, timeStamp: 0, distance: 0, index: 15),
  ChartPoint(decimal: 10, timeStamp: 0, distance: 0, index: 16),
  ChartPoint(decimal: 12, timeStamp: 0, distance: 0, index: 17),
  ChartPoint(decimal: 11, timeStamp: 0, distance: 0, index: 18),
  ChartPoint(decimal: 14.5, timeStamp: 0, distance: 0, index: 19),
  ChartPoint(decimal: 18, timeStamp: 0, distance: 0, index: 20),
  ChartPoint(decimal: 17, timeStamp: 0, distance: 0, index: 21),
  ChartPoint(decimal: 17.5, timeStamp: 0, distance: 0, index: 22),
  ChartPoint(decimal: 15, timeStamp: 0, distance: 0, index: 23),
  ChartPoint(decimal: 16, timeStamp: 0, distance: 0, index: 24),
  ChartPoint(decimal: 16.5, timeStamp: 0, distance: 0, index: 25),
  ChartPoint(decimal: 21, timeStamp: 0, distance: 0, index: 26),
  ChartPoint(decimal: 20, timeStamp: 0, distance: 0, index: 27),
];
